### ISSUE TITLE
1.2.5 Upgrade failed

### ISSUE THREAD

**Issue by Lost-f** [mswgen/oc-updater#10]
0.8.0--0.8.2 no good
stay at this stage
![image](https://user-images.githubusercontent.com/26590981/183240559-26129c2b-6d0c-4d44-99d8-29aa1d3fab7b.png)

**Comment by mswgen** [comment]
Try updating again without any input(mouse move, click, etc) after clicking update.

**Comment by Lost-f** [comment]
still nothing works

**Comment by mswgen** [comment]
Try running the app by running `/Applications/OpenCore\ Updater.app/Contents/MacOS/OpenCore\ Updater` and attach the console output.

**Comment by Lost-f** [comment]
![image](https://user-images.githubusercontent.com/26590981/184139192-6e49d414-7eb5-4d05-8a54-0685ec342377.png)
Please help

**Comment by mswgen** [comment]
Resolved with 1.2.6.
