### ISSUE TITLE
OpenCore Configurator와 호환을 위한 빈 data 처리 개선 요청

### ISSUE THREAD

**Issue by BaikInHyuk** [mswgen/oc-updater#2]
덕분에 오늘 쉽게 0.6.7에서 0.7.5까지 한번에 업데이트 잘 마쳤습니다. 감사합니다.

다만 건의 드릴 게 있어 이슈 하나 남기고 갑니다.

업데이터 사용 후, config.plist에 빈 data 항목에 대해

\<data\/\> 로 값이 들어가게 되는데

OpenCore Configurator 가 해당 항목때문에 config.plist 파일을 열지 못합니다.

\<data\/\> 대신에 \<data\>\<\/data\> 로 빈값 처리가 되었으면 좋겠습니다.

**Comment by BaikInHyuk** [comment]
기존 \<data\>\<\/data\> 로 처리되어있던 config.plist가 패치 후 \<data\/> 로 변하게 되는것 같습니다. npm 모듈 plist의 버그 같아 보이긴 하네요.

**Comment by mswgen** [comment]
사실 <data/>는 <data></data>와 완전히 같은 것이긴 해요.
OpenCore Configurator가 이상하게 된 것 같아요.
plist 모듈을 보면 plist.parse()가 plist를 JavaScript 객체로 바꾸는 것이기 때문에
모듈 버그도 아니고
OpenCore Configurator 버그긴 해요.
그래도 ~~절대 쓰면 안되는~~ OpenCore Configurator 쓰는 사람이 있으니까
plist 수정 후 파일을 다시 읽어서 <data/>만 바꾸는 걸로 패치를 해볼게요.

**Comment by mswgen** [comment]
~~@BaikInHyuk~~

**Comment by BaikInHyuk** [comment]
Clover Configurator 때부터 Configurator 에 익숙하다보니 쓰게 되더라고요 ㅎㅎ 
명시적으로는 같은건 알고있는데 하필 plist 모듈이 그렇게 바꿔버리니... 나중에 올려주신 소스에 개인적으로 파싱만 다시 하는 모듈을 제가 붙여 쓰도록 하겠습니다. 감사합니다.

**Comment by mswgen** [comment]
> Clover Configurator 때부터 Configurator 에 익숙하다보니 쓰게 되더라고요 ㅎㅎ 
> 명시적으로는 같은건 알고있는데 하필 plist 모듈이 그렇게 바꿔버리니... 나중에 올려주신 소스에 개인적으로 파싱만 다시 하는 모듈을 제가 붙여 쓰도록 하겠습니다. 감사합니다.

엌
제가 1.0.7때 개선하려고 했는데...
그래도 plist editor 사용해보세요.

**Comment by mswgen** [comment]
~~@BaikInHyuk~~

**Comment by mswgen** [comment]
> @mswgen 
> 생각보다 우선순위가 높은 issue인 것 같습니다.
> 
> OCC만의 문제라고 생각했으나, 
> Xcode, PlistEdit Pro에서도 동일 증상입니다.
> 제가 테스트해본 것 중에서는 유일하게
> ProperTree만이 잘 작동했습니다.
> 
> Bug Fix가 아닌 개선으로
> 추후 여러 plist에디터들과의 호환성 개선을 위해 
> 수정해 주시면 좋을 것 같습니다. ㅎㅎ

그런가요?
그러면 오늘 학교끝나고 바로 놑북 켜야겠네요.
~~비록 엑팔에는 정지당해서 못들어가지만 개발은 계속됩니다!~~

**Comment by mswgen** [comment]
> > @mswgen 
> > 생각보다 우선순위가 높은 issue인 것 같습니다.
> > 
> > OCC만의 문제라고 생각했으나, 
> > Xcode, PlistEdit Pro에서도 동일 증상입니다.
> > 제가 테스트해본 것 중에서는 유일하게
> > ProperTree만이 잘 작동했습니다.
> > 
> > Bug Fix가 아닌 개선으로
> > 추후 여러 plist에디터들과의 호환성 개선을 위해 
> > 수정해 주시면 좋을 것 같습니다. ㅎㅎ
> 
> 그런가요?
> 그러면 오늘 학교끝나고 바로 놑북 켜야겠네요.
> 오늘 3~4시쯤 1.0.8 나올 예정이니 기대해주세요! ~~문제는 엄마가 못하게 하면...~~ ~~폰코딩이 있긴 하죠~~
> ~~비록 엑팔에는 정지당해서 못들어가지만 개발은 계속됩니다!~~

업데이트: 엄마가 숙제 끝나고 하라네요.
8~9시 쯤 나올 것 같아요.
~~@PKRN0 @BaikInHyuk~~

**Comment by mswgen** [comment]
엄마한테 지금 하게 해달라고 계속 말한 결과 놑북을 켰습니다.
조금만 기다려주세요.

**Comment by mswgen** [comment]
@PKRN0 @BaikInHyuk
릴리즈 1.0.8에서 해결되었습니다.
https://github.com/mswgen/oc-updater/releases/tag/1.0.8

**Comment by mswgen** [comment]
그나저나...
https://osxinfo.net/konu/opencore-updater-opencore-guncelleme-uygulamasi.24433
~~니가 왜 거기서 나와~~
그런데 config.plist 업뎃 중 컴이 갑자기 재부팅됐다는 내용이 있네요...
어떻게 된 거지;;;
