### ISSUE TITLE
1.2.22: JavaScript error while downloading kext

### ISSUE THREAD

**Issue by MatteoBax** [mswgen/oc-updater#24]
JavaScript error while downloading kext with version 1.2.22 of OpenCore Updater.
![Screenshot 2023-11-17 alle 15 22 18](https://github.com/mswgen/oc-updater/assets/98881971/60f04907-d4d3-4b09-8036-80e2bc8dd319)

**Comment by dropdb220** [comment]
Which macOS version are you using?

**Comment by MatteoBax** [comment]
Sonoma 14.0

**Comment by mswgen** [comment]
Which macOS version are you using?

**Comment by dropdb220** [comment]
The cause of this bug was due to a wrong AirportItlwm file. I updated it, so it will work now.

**Comment by MatteoBax** [comment]
Now It works.
