### ISSUE TITLE
Version 1.3.0 is Korean only? [Solved]

### ISSUE THREAD

**Issue by lisavani** [mswgen/oc-updater#27]
Hello MSWGEN, I noticed that version 1.3.0 is Korean only. I tried to use it in an English system anyway and then it crashed. I hope you can fix it.

Kind regards, Lisa

**Comment by dropdb220** [comment]
When does it crash?
If it crashes on srartup, then try creating a folder named 'en.lproj' inside `OpenCore Updater.app/Contents/Resources`. Maybe the `electronLanguages` I added is causing problems(I added `en_US` and `ko` and accidentially tested it only with korean. Maybe it should be `en`, not `en_US`.)
If not, then please let me know where it crashes.
(I can't use my computer right now.)

**Comment by lisavani** [comment]
Hello again, Adding the folder "en.lproj" solved the problem. Thank you very much for your quick reply and of course for creating the updater!

Kind regards, Lisa
