### ISSUE TITLE
1.1.3버전으로 업데이트 사용시 UEFI - Driver 문제

### ISSUE THREAD

**Issue by sloseee** [mswgen/oc-updater#3]
이름이 전부 삭제돼고 직접 다시 인식시켜줘야하는 문제요.

**Comment by mswgen** [comment]
혹시 OC 몇에서 업데이트했나요?

**Comment by mswgen** [comment]
@sloseee

**Comment by sloseee** [comment]
063이요

2021년 12월 23일 (목) 오후 10:28, mswgen ***@***.***>님이 작성:

**Comment by mswgen** [comment]
@sloseee 혹시 기존에 VBoxHfs.efi를 사용하셨나요?

**Comment by mswgen** [comment]
@sloseee ...
